server:
    port: 8080

#openidconnect authentication
openidconnect:
    issuer-uri: https://auth.ekogui.gov.co:9443/oauth2endpoints/token
    issuer: https://auth.ekogui.gov.co:9443/oauth2endpoints/token
    authorizationEndpointUri: https://auth.ekogui.gov.co:9443/oauth2/authorize
    tokenEndpointUri: https://auth.ekogui.gov.co:9443/oauth2/token
    userInfoUri: https://auth.ekogui.gov.co:9443/oauth2/userinfo?schema=openid
    clientId: fq4obd6a9N9upapYqrpsrKIzEiga
    clientSecret: zaHMfRAafBQSKZJpADqnqASek4oa
    redirectUri: http://192.168.40.145:8080/auth/openid_connect_login


spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        url: jdbc:h2:mem:jhipster;DB_CLOSE_DELAY=-1
        databaseName: 
        serverName: 
        username: 
        password: 

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: jhipsteroidcsample

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M
